from pathlib import Path
p=Path('app.py')
s=p.read_text(encoding='utf-8')
# CSS refinements
s=s.replace('[data-testid="stSidebar"]{background:#ffffff;border-right:1px solid #e5e9f0}', '[data-testid="stSidebar"]{background:#111827;border-right:0;color:#f8fafc}\n[data-testid="stSidebar"] *{color:#e5e7eb}\n[data-testid="stSidebar"] .rz-brand{color:#ffffff}\n[data-testid="stSidebar"] .rz-brand span{color:#60a5fa}\n[data-testid="stSidebar"] [data-baseweb="select"]>div{background:#1f2937;border-color:#374151}\n[data-testid="stSidebar"] [role="radiogroup"] label{color:#cbd5e1}\n[data-testid="stSidebar"] [role="radiogroup"] label:has(input:checked){background:#1d4ed8;color:#fff}',1)
s=s.replace('[data-testid="stSidebar"] [data-testid="stRadio"] label:hover{background:#f2f6ff}', '[data-testid="stSidebar"] [data-testid="stRadio"] label:hover{background:#1f2937}',1)
s=s.replace('.rz-welcome{background:#fff;border:1px solid #e5e9f0;border-radius:14px;padding:17px 19px;margin-bottom:14px;box-shadow:0 1px 2px rgba(16,24,40,.025)}', '.rz-welcome{background:linear-gradient(135deg,#1d4ed8,#2563eb);border:0;border-radius:16px;padding:18px 20px;margin-bottom:14px;box-shadow:0 8px 22px rgba(37,99,235,.12)}',1)
s=s.replace('.rz-welcome-title{font-size:1.1rem;font-weight:760;color:#172033}.rz-welcome-sub{color:#667085;font-size:.87rem;margin-top:3px}', '.rz-welcome-title{font-size:1.08rem;font-weight:760;color:#fff}.rz-welcome-sub{color:#dbeafe;font-size:.86rem;margin-top:3px}',1)
s=s.replace('.block-container{padding-top:1.25rem;padding-bottom:2.5rem;max-width:1380px}', '.block-container{padding-top:1.1rem;padding-bottom:2.5rem;max-width:1240px}',1)
s=s.replace('[data-testid="stMetric"]{background:#fff;border:1px solid #e5e9f0;border-radius:14px;padding:16px 18px;box-shadow:0 1px 3px rgba(16,24,40,.04)}', '[data-testid="stMetric"]{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:15px 17px;box-shadow:0 4px 14px rgba(16,24,40,.035)}',1)
# Make dashboard more compact: actions and attention side-by-side, remove redundant lower alerts
old='''    st.markdown('<div class="rz-section">O que você precisa resolver</div>', unsafe_allow_html=True)\n    priorities = action_items(profile, transactions, invoices, das_rows, obligations, limit, year_revenue)\n    for idx, item in enumerate(priorities[:4]):\n        a,b = st.columns([5,1])\n        with a:\n            level = "danger" if item["priority"] == 1 else "warn" if item["priority"] == 2 else "info" if item["priority"] == 3 else "ok"\n            alert_box(level, item["title"], item["detail"])\n        with b:\n            if item["page"] != "Dashboard" and st.button("Resolver", key=f"priority_{idx}", use_container_width=True):\n                st.session_state["_navigate_to"] = item["page"]\n                st.rerun()\n\n    st.markdown('<div class="rz-section">Atalhos</div>', unsafe_allow_html=True)\n    q1,q2,q3,q4 = st.columns(4)\n    if q1.button("+ Lançamento", use_container_width=True): st.session_state["_navigate_to"]="Movimentações"; st.rerun()\n    if q2.button("Importar extrato", use_container_width=True): st.session_state["_navigate_to"]="Importar Extrato"; st.rerun()\n    if q3.button("Ver DAS", use_container_width=True): st.session_state["_navigate_to"]="DAS"; st.rerun()\n    if q4.button("Obrigações", use_container_width=True): st.session_state["_navigate_to"]="Obrigações"; st.rerun()'''
new='''    main_col, side_col = st.columns([1.65,1], gap="large")\n    priorities = action_items(profile, transactions, invoices, das_rows, obligations, limit, year_revenue)\n    with main_col:\n        st.markdown('<div class="rz-section">O que precisa da sua atenção</div>', unsafe_allow_html=True)\n        for idx, item in enumerate(priorities[:3]):\n            a,b = st.columns([4.6,1.15])\n            with a:\n                level = "danger" if item["priority"] == 1 else "warn" if item["priority"] == 2 else "info" if item["priority"] == 3 else "ok"\n                alert_box(level, item["title"], item["detail"])\n            with b:\n                if item["page"] != "Dashboard" and st.button("Resolver", key=f"priority_{idx}", use_container_width=True):\n                    st.session_state["_navigate_to"] = item["page"]\n                    st.rerun()\n    with side_col:\n        st.markdown('<div class="rz-section">Acesso rápido</div>', unsafe_allow_html=True)\n        if st.button("＋ Nova movimentação", use_container_width=True): st.session_state["_navigate_to"]="Movimentações"; st.rerun()\n        if st.button("↥ Importar extrato", use_container_width=True): st.session_state["_navigate_to"]="Importar Extrato"; st.rerun()\n        if st.button("▣ Ver impostos e DAS", use_container_width=True): st.session_state["_navigate_to"]="Central Fiscal"; st.rerun()\n        if st.button("✓ Ver obrigações", use_container_width=True): st.session_state["_navigate_to"]="Obrigações"; st.rerun()'''
if old in s: s=s.replace(old,new,1)
# Avoid duplicated alert column below; use organization card instead
old2='''    with right:\n        st.markdown('<div class="rz-section">Avisos importantes</div>', unsafe_allow_html=True)\n        for level,title,text in build_alerts(year_revenue,limit,das_rows,obligations,profile):\n            alert_box(level,title,text)'''
new2='''    with right:\n        st.markdown('<div class="rz-section">Organização do MEI</div>', unsafe_allow_html=True)\n        health_score, health_notes = mei_health_score(profile, year_revenue, limit, das_rows, obligations)\n        st.metric("Índice de organização", f"{health_score}/100")\n        st.progress(health_score/100)\n        if health_notes:\n            for note in health_notes[:3]: st.caption(f"• {note}")\n        else:\n            st.success("Tudo organizado com os dados cadastrados.")'''
if old2 in s: s=s.replace(old2,new2,1)
# Remove duplicate organization block later
start=s.find("    st.markdown('<div class=\"rz-section\">Como está sua organização</div>', unsafe_allow_html=True)")
if start!=-1:
    end=s.find('    with st.expander("Checklist de configuração do MEI"', start)
    if end!=-1: s=s[:start]+s[end:]
p.write_text(s,encoding='utf-8')
print('dashboard v2 polished')
