from pathlib import Path

p = Path("app.py")
s = p.read_text(encoding="utf-8")

s = s.replace(
    "from reports import dasn_summary_pdf, monthly_report_pdf\n",
    "from reports import dasn_summary_pdf, monthly_report_pdf, financial_summary_pdf, closing_summary_pdf\n",
    1,
)
if "from product_core import" not in s:
    s = s.replace(
        "from business_tools import monthly_closing, financial_analysis, consistency_checks\n",
        "from business_tools import monthly_closing, financial_analysis, consistency_checks\nfrom product_core import NAV_GROUPS, group_for_page, action_items, reconciliation_summary, assistant_answer\n",
        1,
    )

old_sidebar_start = '''pending_page = st.session_state.pop("_navigate_to", None)\nif pending_page:\n    st.session_state["nav_page"] = pending_page\n\nwith st.sidebar:\n    st.markdown('<div class="rz-brand">RAZYNC <span>PRO</span></div>', unsafe_allow_html=True)\n    st.caption("Ecossistema Razync • MEI")\n    st.divider()\n    page = st.radio("Navegação", ["Dashboard","Movimentações","Importar Extrato","Fluxo de Caixa","Análise Financeira","Fechamento Mensal","Relatório Mensal","Notas Fiscais","DAS","DASN-SIMEI","Obrigações","Clientes e Fornecedores","Empregado","Documentos","Assistente Razync","Meu MEI","Backup"], label_visibility="collapsed", key="nav_page")\n    st.divider()\n    st.caption("Modo de desenvolvimento • acesso direto")\n'''
new_sidebar = '''pending_page = st.session_state.pop("_navigate_to", None)\nif pending_page:\n    target_group = group_for_page(pending_page)\n    st.session_state["nav_group"] = target_group\n    st.session_state[f"nav_page_{target_group}"] = pending_page\n\nwith st.sidebar:\n    st.markdown('<div class="rz-brand">RAZYNC <span>PRO</span></div>', unsafe_allow_html=True)\n    st.caption("Ecossistema Razync • Gestão completa do MEI")\n    st.divider()\n    groups = list(NAV_GROUPS.keys())\n    if st.session_state.get("nav_group") not in groups:\n        st.session_state["nav_group"] = "Visão Geral"\n    selected_group = st.selectbox("Área", groups, key="nav_group")\n    group_pages = NAV_GROUPS[selected_group]\n    page_key = f"nav_page_{selected_group}"\n    if st.session_state.get(page_key) not in group_pages:\n        st.session_state[page_key] = group_pages[0]\n    page = st.radio("Navegação", group_pages, label_visibility="collapsed", key=page_key)\n    st.divider()\n    st.caption("Modo de desenvolvimento • acesso direto")\n'''
if old_sidebar_start in s:
    s = s.replace(old_sidebar_start, new_sidebar, 1)

metric_marker = '''    c1,c2,c3,c4,c5 = st.columns(5)\n    c1.metric("Receita no ano",brl(year_revenue)); c2.metric("Despesas no ano",brl(year_expense)); c3.metric("Resultado estimado",brl(year_revenue-year_expense)); c4.metric("Limite utilizado",f"{limit_pct:.1f}%"); c5.metric("Documentos",len(docs))\n    st.caption("Ações rápidas")\n'''
metric_new = '''    c1,c2,c3,c4,c5 = st.columns(5)\n    c1.metric("Receita no ano",brl(year_revenue)); c2.metric("Despesas no ano",brl(year_expense)); c3.metric("Resultado estimado",brl(year_revenue-year_expense)); c4.metric("Limite utilizado",f"{limit_pct:.1f}%"); c5.metric("Documentos",len(docs))\n\n    st.subheader("Prioridades de hoje")\n    priorities = action_items(profile, transactions, invoices, das_rows, obligations, limit, year_revenue)\n    for idx, item in enumerate(priorities[:4]):\n        a,b = st.columns([5,1])\n        with a:\n            level = "danger" if item["priority"] == 1 else "warn" if item["priority"] == 2 else "info" if item["priority"] == 3 else "ok"\n            alert_box(level, item["title"], item["detail"])\n        with b:\n            if item["page"] != "Dashboard" and st.button("Resolver", key=f"priority_{idx}", use_container_width=True):\n                st.session_state["_navigate_to"] = item["page"]\n                st.rerun()\n\n    st.caption("Ações rápidas")\n'''
if metric_marker in s and "Prioridades de hoje" not in s:
    s = s.replace(metric_marker, metric_new, 1)

flow_marker = '''elif page == "Fluxo de Caixa":\n'''
conciliation_page = '''elif page == "Conciliação":\n    header("Conciliação","Confira notas, receitas e possíveis duplicidades antes do fechamento mensal.")\n    rec = reconciliation_summary(transactions, invoices)\n    c1,c2,c3 = st.columns(3)\n    c1.metric("Notas emitidas", rec["total_invoices"])\n    c2.metric("Notas conciliadas", rec["reconciled_invoices"])\n    c3.metric("Possíveis duplicidades", rec["possible_duplicate_transactions"])\n    pending_inv = rec["pending_invoices"]\n    st.subheader("Notas pendentes de conciliação")\n    if pending_inv.empty:\n        st.success("Todas as notas com número informado estão conciliadas com receitas cadastradas.")\n    else:\n        st.dataframe(pending_inv, use_container_width=True, hide_index=True, column_config={"Valor":st.column_config.NumberColumn("Valor", format="R$ %.2f")})\n        selected_invoice = st.selectbox("Conciliar nota", pending_inv["ID"].tolist(), key="rec_invoice")\n        source = invoices[invoices["id"] == selected_invoice].iloc[0]\n        if st.button("Criar receita a partir desta nota", type="primary", use_container_width=True):\n            issue = source["issue_date"]\n            tx_date_value = issue.date() if hasattr(issue, "date") else issue\n            add_transaction(uid, tx_date=tx_date_value, tx_type="Receita", description=source.get("description") or f"Nota {source.get('number') or ''}", category="Serviços" if source.get("invoice_type") == "Serviço" else "Vendas", value=float(source.get("amount") or 0), document_number=str(source.get("number") or ""), counterparty=str(source.get("customer") or ""), payment_method="Outro")\n            st.success("Receita criada e nota conciliada.")\n            st.rerun()\n    st.subheader("Validações")\n    checks = pd.DataFrame(consistency_checks(transactions, invoices, das_rows))\n    st.dataframe(checks, use_container_width=True, hide_index=True)\n    if st.button("Importar novo extrato", use_container_width=True):\n        st.session_state["_navigate_to"] = "Importar Extrato"\n        st.rerun()\n\n'''+flow_marker
if flow_marker in s and 'elif page == "Conciliação"' not in s:
    s = s.replace(flow_marker, conciliation_page, 1)

closing_marker = '''elif page == "Fechamento Mensal":\n'''
central_fiscal = '''elif page == "Central Fiscal":\n    header("Central Fiscal MEI","Uma visão única do limite, DAS, relatório mensal, DASN-SIMEI e obrigações.")\n    overdue_das = [d for d in das_rows if das_status(d.get("status","Pendente"), d.get("due_date")) == "Atrasado"]\n    pending_das = [d for d in das_rows if das_status(d.get("status","Pendente"), d.get("due_date")) == "Pendente"]\n    c1,c2,c3,c4 = st.columns(4)\n    c1.metric("Faturamento no ano", brl(year_revenue))\n    c2.metric("Limite restante", brl(max(limit-year_revenue,0)))\n    c3.metric("DAS em atraso", len(overdue_das))\n    c4.metric("DAS pendentes", len(pending_das))\n    st.progress(min(limit_pct/100, 1.0))\n    st.caption(f"{limit_pct:.1f}% do limite monitorado utilizado.")\n\n    st.subheader("Próximas obrigações")\n    auto = pd.DataFrame(automatic_obligations(CURRENT_YEAR, opening))\n    if not auto.empty:\n        future = auto[auto["Vencimento"] >= date.today()].sort_values("Vencimento").head(6)\n        st.dataframe(future, use_container_width=True, hide_index=True, column_config={"Vencimento":st.column_config.DateColumn("Vencimento", format="DD/MM/YYYY")})\n\n    st.subheader("Acessos fiscais")\n    a,b,c,d = st.columns(4)\n    if a.button("DAS", use_container_width=True): st.session_state["_navigate_to"]="DAS"; st.rerun()\n    if b.button("Relatório Mensal", use_container_width=True): st.session_state["_navigate_to"]="Relatório Mensal"; st.rerun()\n    if c.button("DASN-SIMEI", use_container_width=True): st.session_state["_navigate_to"]="DASN-SIMEI"; st.rerun()\n    if d.button("Obrigações", use_container_width=True): st.session_state["_navigate_to"]="Obrigações"; st.rerun()\n    st.info("O Razync Pro organiza e confere os dados. Envios e pagamentos oficiais continuam nos serviços governamentais correspondentes.")\n\n'''+closing_marker
if closing_marker in s and 'elif page == "Central Fiscal"' not in s:
    s = s.replace(closing_marker, central_fiscal, 1)

assistant_marker = '''elif page == "Assistente Razync":\n'''
reports_center = '''elif page == "Central de Relatórios":\n    header("Central de Relatórios","Gere documentos gerenciais e fiscais a partir dos dados já cadastrados.")\n    years = {CURRENT_YEAR}\n    if not transactions.empty:\n        years.update(int(y) for y in transactions["tx_date"].dt.year.unique())\n    report_year = st.selectbox("Ano", sorted(years, reverse=True), key="report_center_year")\n    report_month = st.selectbox("Mês para fechamento", list(range(1,13)), index=max(date.today().month-1,0), key="report_center_month")\n    analysis_report = financial_analysis(transactions, int(report_year))\n    closing_report = monthly_closing(transactions, invoices, docs, das_rows, int(report_year), int(report_month))\n    monthly_data = monthly_rows(transactions, int(report_year))\n    services_report, sales_report = category_totals_for_dasn(transactions, int(report_year))\n    active_employee_report = any(e.get("status") == "Ativo" for e in employees)\n\n    st.subheader("Relatórios disponíveis")\n    r1,r2 = st.columns(2)\n    with r1:\n        st.download_button("Análise financeira em PDF", financial_summary_pdf(profile, int(report_year), analysis_report), f"analise_financeira_{report_year}.pdf", "application/pdf", use_container_width=True)\n        st.download_button("Relatório Mensal em PDF", monthly_report_pdf(profile, int(report_year), monthly_data), f"relatorio_mensal_{report_year}.pdf", "application/pdf", use_container_width=True)\n    with r2:\n        st.download_button("Fechamento mensal em PDF", closing_summary_pdf(profile, int(report_year), int(report_month), closing_report), f"fechamento_{report_year}_{int(report_month):02d}.pdf", "application/pdf", use_container_width=True)\n        st.download_button("Resumo DASN-SIMEI em PDF", dasn_summary_pdf(profile, int(report_year), services_report, sales_report, active_employee_report), f"dasn_{report_year}.pdf", "application/pdf", use_container_width=True)\n    st.caption("Todos os relatórios são gerados com base nos dados cadastrados no Razync Pro e devem ser conferidos antes de uso oficial.")\n\n'''+assistant_marker
if assistant_marker in s and 'elif page == "Central de Relatórios"' not in s:
    s = s.replace(assistant_marker, reports_center, 1)

start = s.find('elif page == "Assistente Razync":')
end = s.find('\nelif page == "Meu MEI":', start)
if start != -1 and end != -1:
    new_assistant = '''elif page == "Assistente Razync":\n    header("Assistente Razync","Pergunte sobre faturamento, despesas, limite, DAS e conciliação usando os dados do seu MEI.")\n    st.caption("Sugestões: Quanto posso faturar? • Quanto sobrou? • Quais são meus maiores gastos? • Tenho DAS atrasado? • Existem notas pendentes?")\n    question = st.text_input("Pergunte sobre seu MEI", key="assistant_question")\n    if question:\n        st.info(assistant_answer(question, transactions, invoices, das_rows, limit, CURRENT_YEAR))\n    st.divider()\n    st.caption("O Assistente Razync usa os dados cadastrados no sistema. Para situações fiscais especiais, desenquadramento ou decisões profissionais, confirme a orientação em fonte oficial ou com profissional habilitado.")\n'''
    s = s[:start] + new_assistant + s[end:]

p.write_text(s, encoding="utf-8")
print("product restructure applied")
