from pathlib import Path

p = Path('app.py')
s = p.read_text(encoding='utf-8')

old_nav = '["Dashboard","Movimentações","Relatório Mensal","Notas Fiscais","DAS","DASN-SIMEI","Obrigações","Clientes e Fornecedores","Empregado","Documentos","Assistente Razync","Meu MEI","Backup"]'
new_nav = '["Dashboard","Movimentações","Fluxo de Caixa","Relatório Mensal","Notas Fiscais","DAS","DASN-SIMEI","Obrigações","Clientes e Fornecedores","Empregado","Documentos","Assistente Razync","Meu MEI","Backup"]'
if old_nav in s:
    s = s.replace(old_nav, new_nav, 1)

marker = '''def category_totals_for_dasn(df: pd.DataFrame, year: int) -> tuple[float,float]:\n    if df.empty:\n        return 0.0,0.0\n    cur = df[(df["tx_type"]=="Receita") & (df["tx_date"].dt.year==year)]\n    services = float(cur[cur["category"].isin(["Serviços","Serviço"])]["value"].sum())\n    sales = float(cur["value"].sum()) - services\n    return services, sales\n'''
helper = marker + '''\n\ndef cashflow_monthly(df: pd.DataFrame, year: int) -> pd.DataFrame:\n    rows = []\n    for month in range(1, 13):\n        cur = df[df["tx_date"].dt.year == year] if not df.empty else df\n        cur = cur[cur["tx_date"].dt.month == month] if not cur.empty else cur\n        entradas = float(cur[cur["tx_type"] == "Receita"]["value"].sum()) if not cur.empty else 0.0\n        saidas = float(cur[cur["tx_type"] == "Despesa"]["value"].sum()) if not cur.empty else 0.0\n        rows.append({"Mês": calendar.month_name[month], "Entradas": entradas, "Saídas": saidas, "Resultado": entradas-saidas})\n    out = pd.DataFrame(rows)\n    out["Saldo acumulado"] = out["Resultado"].cumsum()\n    return out\n\ndef mei_health_score(profile: dict, revenue: float, limit: float, das_rows: list, obligations: list) -> tuple[int, list[str]]:\n    score = 100\n    notes = []\n    if not profile.get("cnpj"):\n        score -= 20; notes.append("Complete os dados do CNPJ em Meu MEI.")\n    if not profile.get("main_activity"):\n        score -= 10; notes.append("Informe a atividade principal.")\n    if limit and revenue / limit >= 0.8:\n        score -= 20; notes.append("Faturamento acima de 80% do limite monitorado.")\n    overdue = [d for d in das_rows if das_status(d.get("status", "Pendente"), d.get("due_date")) == "Atrasado"]\n    if overdue:\n        score -= min(30, len(overdue) * 10); notes.append(f"Existem {len(overdue)} DAS em atraso.")\n    late_obs = [o for o in obligations if o.get("status") != "Concluído" and o.get("due_date") and o.get("due_date") < date.today()]\n    if late_obs:\n        score -= min(20, len(late_obs) * 5); notes.append(f"Existem {len(late_obs)} obrigações vencidas.")\n    return max(score, 0), notes\n'''
if marker in s and 'def cashflow_monthly' not in s:
    s = s.replace(marker, helper, 1)

dashboard_marker = '''    st.subheader("Últimos lançamentos")\n    if transactions.empty:\n        st.info("Cadastre sua primeira movimentação.")\n    else:\n        st.dataframe(transactions.head(10)[["tx_date","tx_type","description","counterparty","value"]],use_container_width=True,hide_index=True,column_config={"tx_date":st.column_config.DateColumn("Data",format="DD/MM/YYYY"),"value":st.column_config.NumberColumn("Valor",format="R$ %.2f")})\n'''
dashboard_new = dashboard_marker + '''\n    st.subheader("Saúde do seu MEI")\n    health_score, health_notes = mei_health_score(profile, year_revenue, limit, das_rows, obligations)\n    a,b = st.columns([1,2])\n    with a:\n        st.metric("Índice de organização", f"{health_score}/100")\n        st.progress(health_score/100)\n    with b:\n        if health_notes:\n            for note in health_notes:\n                st.caption(f"• {note}")\n        else:\n            st.success("Seu cadastro e obrigações monitoradas estão organizados.")\n\n    with st.expander("Checklist de configuração do MEI", expanded=not bool(profile.get("cnpj"))):\n        checklist = [\n            ("Dados do CNPJ preenchidos", bool(profile.get("cnpj"))),\n            ("Atividade principal informada", bool(profile.get("main_activity"))),\n            ("Data de abertura cadastrada", bool(profile.get("opening_date"))),\n            ("Primeira movimentação registrada", not transactions.empty),\n            ("Calendário do DAS criado", bool(das_rows)),\n            ("Primeiro documento armazenado", bool(docs)),\n        ]\n        for label, done in checklist:\n            st.write(("✅ " if done else "⬜ ") + label)\n'''
if dashboard_marker in s and 'Índice de organização' not in s:
    s = s.replace(dashboard_marker, dashboard_new, 1)

flow_insert = '''elif page == "Relatório Mensal":\n'''
flow_page = '''elif page == "Fluxo de Caixa":\n    header("Fluxo de Caixa","Acompanhe entradas, saídas, resultado mensal e evolução do saldo do negócio.")\n    years = {CURRENT_YEAR}\n    if not transactions.empty:\n        years.update(int(y) for y in transactions["tx_date"].dt.year.unique())\n    flow_year = st.selectbox("Ano do fluxo de caixa", sorted(years, reverse=True))\n    flow = cashflow_monthly(transactions, int(flow_year))\n    c1,c2,c3 = st.columns(3)\n    c1.metric("Entradas", brl(float(flow["Entradas"].sum())))\n    c2.metric("Saídas", brl(float(flow["Saídas"].sum())))\n    c3.metric("Resultado", brl(float(flow["Resultado"].sum())))\n    chart = flow.melt(id_vars=["Mês"], value_vars=["Entradas","Saídas"], var_name="Tipo", value_name="Valor")\n    fig = px.bar(chart, x="Mês", y="Valor", color="Tipo", barmode="group")\n    fig.update_layout(height=350, margin=dict(l=0,r=0,t=10,b=0), xaxis_title="", yaxis_title="Valor")\n    st.plotly_chart(fig, use_container_width=True)\n    fig2 = px.line(flow, x="Mês", y="Saldo acumulado", markers=True)\n    fig2.update_layout(height=300, margin=dict(l=0,r=0,t=10,b=0), xaxis_title="", yaxis_title="Saldo acumulado")\n    st.plotly_chart(fig2, use_container_width=True)\n    st.dataframe(flow, use_container_width=True, hide_index=True, column_config={c:st.column_config.NumberColumn(c, format="R$ %.2f") for c in ["Entradas","Saídas","Resultado","Saldo acumulado"]})\n\n'''+flow_insert
if flow_insert in s and 'elif page == "Fluxo de Caixa"' not in s:
    s = s.replace(flow_insert, flow_page, 1)

p.write_text(s, encoding='utf-8')
print('upgrade applied')
# trigger upgrade workflow
