create table if not exists public.ai_action_drafts (
    id bigint generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    action_key varchar(64) not null,
    conversation_id bigint references public.ai_conversations(id) on delete set null,
    channel varchar(20) not null default 'web',
    action_type varchar(40) not null,
    status varchar(20) not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
    summary varchar(500) not null default '',
    draft_json text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, action_key)
);

create index if not exists ix_ai_action_drafts_user_status
    on public.ai_action_drafts (user_id, status, updated_at desc);
create index if not exists ix_ai_action_drafts_conversation
    on public.ai_action_drafts (conversation_id);

create table if not exists public.ai_feedback (
    id bigint generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    conversation_id bigint references public.ai_conversations(id) on delete set null,
    message_key varchar(64) not null,
    helpful boolean not null,
    note varchar(500) not null default '',
    created_at timestamptz not null default now(),
    unique (user_id, message_key)
);
create index if not exists ix_ai_feedback_conversation
    on public.ai_feedback (conversation_id);

alter table public.ai_action_drafts enable row level security;
alter table public.ai_feedback enable row level security;

revoke all on table public.ai_action_drafts from anon, authenticated;
revoke all on table public.ai_feedback from anon, authenticated;
revoke all on sequence public.ai_action_drafts_id_seq from anon, authenticated;
revoke all on sequence public.ai_feedback_id_seq from anon, authenticated;

drop policy if exists ai_action_drafts_backend_only on public.ai_action_drafts;
create policy ai_action_drafts_backend_only on public.ai_action_drafts
    for all to anon, authenticated using (false) with check (false);

drop policy if exists ai_feedback_backend_only on public.ai_feedback;
create policy ai_feedback_backend_only on public.ai_feedback
    for all to anon, authenticated using (false) with check (false);

comment on table public.ai_action_drafts is 'Rascunhos confirmáveis da IA, acessíveis somente pelo backend Razync.';
comment on table public.ai_feedback is 'Avaliações de respostas da IA, acessíveis somente pelo backend Razync.';
