-- Applied to project etimfgenlludorrftapb as migration audit_history.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  table_name text not null,
  record_id text,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);
create index if not exists ix_audit_logs_user_created on public.audit_logs (user_id, created_at desc);
alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon, authenticated;
grant select on public.audit_logs to authenticated;
drop policy if exists audit_logs_owner_select on public.audit_logs;
create policy audit_logs_owner_select on public.audit_logs for select to authenticated
using (exists (select 1 from public.users u where u.id = audit_logs.user_id and u.auth_user_id = (select auth.uid())));

create or replace function public.razync_capture_audit()
returns trigger language plpgsql security invoker set search_path = public, pg_temp as $$
declare before_row jsonb; after_row jsonb; owner_id bigint; row_identifier text;
begin
  before_row := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) - 'password_hash' - 'content' else null end;
  after_row := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) - 'password_hash' - 'content' else null end;
  owner_id := coalesce((after_row->>'user_id')::bigint, (before_row->>'user_id')::bigint);
  row_identifier := coalesce(after_row->>'id', before_row->>'id');
  if owner_id is not null then
    insert into public.audit_logs(user_id,table_name,record_id,action,old_data,new_data)
    values(owner_id,tg_table_name,row_identifier,tg_op,before_row,after_row);
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;
revoke all on function public.razync_capture_audit() from public, anon, authenticated;
do $audit$
declare table_name text;
begin
  foreach table_name in array array['mei_profiles','transactions','das_items','documents','invoices','contacts','employees','obligations','recurring_transactions']
  loop
    execute format('drop trigger if exists razync_audit_changes on public.%I', table_name);
    execute format('create trigger razync_audit_changes after insert or update or delete on public.%I for each row execute function public.razync_capture_audit()', table_name);
  end loop;
end
$audit$;
