create table if not exists public.ai_conversations (
    id bigint generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    title varchar(120) not null default 'Nova conversa',
    channel varchar(20) not null default 'web' check (channel in ('web', 'whatsapp')),
    archived boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_ai_conversations_user_updated
    on public.ai_conversations (user_id, updated_at desc);

create table if not exists public.ai_messages (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references public.ai_conversations(id) on delete cascade,
    user_id integer not null references public.users(id) on delete cascade,
    role varchar(20) not null check (role in ('user', 'assistant', 'system')),
    content text not null check (char_length(content) between 1 and 16000),
    metadata_json text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_ai_messages_conversation_created
    on public.ai_messages (conversation_id, created_at, id);
create index if not exists ix_ai_messages_user
    on public.ai_messages (user_id);

alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;

revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.ai_messages from anon, authenticated;
revoke all on sequence public.ai_conversations_id_seq from anon, authenticated;
revoke all on sequence public.ai_messages_id_seq from anon, authenticated;

comment on table public.ai_conversations is
'Conversas persistentes e privadas do Assistente Razync. Acesso somente pelo backend do aplicativo.';
comment on table public.ai_messages is
'Mensagens das conversas do Assistente Razync, sempre vinculadas ao usuario proprietário.';

