-- Recurring financial entries with tenant isolation.
create table if not exists public.recurring_transactions (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  tx_type text not null check (tx_type in ('Receita', 'Despesa')),
  description text not null check (char_length(trim(description)) > 0),
  category text not null default 'Outros',
  value numeric(14,2) not null check (value > 0),
  payment_method text not null default 'Outro',
  frequency text not null check (frequency in ('Semanal', 'Mensal', 'Anual')),
  next_date date not null,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (end_date is null or end_date >= next_date)
);

create index if not exists recurring_transactions_user_id_idx
  on public.recurring_transactions (user_id);
create index if not exists recurring_transactions_due_idx
  on public.recurring_transactions (user_id, next_date)
  where active = true;

alter table public.recurring_transactions enable row level security;

drop policy if exists recurring_transactions_owner on public.recurring_transactions;
create policy recurring_transactions_owner
  on public.recurring_transactions
  for all
  to authenticated
  using (
    exists (
      select 1 from public.users u
      where u.id = recurring_transactions.user_id
        and u.auth_user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.users u
      where u.id = recurring_transactions.user_id
        and u.auth_user_id = (select auth.uid())
    )
  );

grant select, insert, update, delete
  on public.recurring_transactions to authenticated, service_role;
grant usage, select
  on sequence public.recurring_transactions_id_seq to authenticated, service_role;

alter table public.transactions
  add column if not exists recurring_transaction_id bigint
  references public.recurring_transactions(id) on delete set null;

create unique index if not exists transactions_recurring_date_uidx
  on public.transactions (recurring_transaction_id, tx_date)
  where recurring_transaction_id is not null;
