create table if not exists public.ai_action_executions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    action_key varchar(64) not null,
    action_type varchar(40) not null,
    channel varchar(20) not null default 'web' check (channel in ('web', 'whatsapp')),
    status varchar(20) not null default 'processing' check (status in ('processing', 'completed', 'failed', 'undone')),
    summary varchar(500) not null default '',
    receipt_json text,
    error_message varchar(500),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (user_id, action_key)
);

create index if not exists ix_ai_action_executions_user_created
    on public.ai_action_executions (user_id, created_at desc);

alter table public.ai_action_executions enable row level security;
revoke all on table public.ai_action_executions from anon, authenticated;
revoke all on sequence public.ai_action_executions_id_seq from anon, authenticated;

drop policy if exists ai_action_executions_backend_only on public.ai_action_executions;
create policy ai_action_executions_backend_only
on public.ai_action_executions
for all
to anon, authenticated
using (false)
with check (false);

comment on table public.ai_action_executions is
'Registro backend-only para idempotência, recibos e histórico das automações confirmadas pela IA.';

