[theme]
base = "light"
primaryColor = "#08B9EF"
backgroundColor = "#F1F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111C27"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "viewer"
