[theme]
base = "light"
primaryColor = "#087F79"
backgroundColor = "#F5F7F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172C35"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
showErrorDetails = false
showErrorLinks = false

